spring.application.name=crudDemo

#JDBC Driver configs
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=root
spring.datasource.password=Warzoneelover579@

spring.security.user.nam=user
spring.security.user.password=123@
